"""Fresh start

Revision ID: c6070c0ab463
Revises: 0040b7c3204d
Create Date: 2025-05-08 12:39:38.852090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6070c0ab463'
down_revision = '0040b7c3204d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_cctv')
    with op.batch_alter_table('cctv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('altitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('camera_type', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('camera_angle', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('resolution', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('recording_status', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('storage_duration_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('installation_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('last_maintenance_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('last_active_timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('error_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('auto_restart', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_critical', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('face_crop_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('frame_match_interval', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('alert_group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('zone', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('assigned_guard', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('camera_model', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('video_download_location', sa.Text(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('stream_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cctv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stream_url', sa.VARCHAR(length=500), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('video_download_location')
        batch_op.drop_column('camera_model')
        batch_op.drop_column('assigned_guard')
        batch_op.drop_column('zone')
        batch_op.drop_column('site_id')
        batch_op.drop_column('alert_group_id')
        batch_op.drop_column('frame_match_interval')
        batch_op.drop_column('face_crop_enabled')
        batch_op.drop_column('is_critical')
        batch_op.drop_column('auto_restart')
        batch_op.drop_column('error_count')
        batch_op.drop_column('last_active_timestamp')
        batch_op.drop_column('status')
        batch_op.drop_column('last_maintenance_date')
        batch_op.drop_column('installation_date')
        batch_op.drop_column('storage_duration_days')
        batch_op.drop_column('recording_status')
        batch_op.drop_column('resolution')
        batch_op.drop_column('camera_angle')
        batch_op.drop_column('camera_type')
        batch_op.drop_column('altitude')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('description')
        batch_op.drop_column('location')

    op.create_table('_alembic_tmp_cctv',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('cctv_id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.TEXT(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('altitude', sa.FLOAT(), nullable=False),
    sa.Column('camera_type', sa.TEXT(), nullable=False),
    sa.Column('camera_angle', sa.TEXT(), nullable=False),
    sa.Column('resolution', sa.TEXT(), nullable=False),
    sa.Column('recording_status', sa.TEXT(), nullable=False),
    sa.Column('storage_duration_days', sa.INTEGER(), nullable=False),
    sa.Column('installation_date', sa.DATE(), nullable=False),
    sa.Column('last_maintenance_date', sa.DATE(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('last_active_timestamp', sa.DATETIME(), nullable=False),
    sa.Column('error_count', sa.INTEGER(), nullable=False),
    sa.Column('auto_restart', sa.BOOLEAN(), nullable=False),
    sa.Column('is_critical', sa.BOOLEAN(), nullable=False),
    sa.Column('face_crop_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('frame_match_interval', sa.INTEGER(), nullable=False),
    sa.Column('alert_group_id', sa.INTEGER(), nullable=True),
    sa.Column('site_id', sa.INTEGER(), nullable=True),
    sa.Column('zone', sa.TEXT(), nullable=False),
    sa.Column('assigned_guard', sa.INTEGER(), nullable=True),
    sa.Column('camera_model', sa.TEXT(), nullable=True),
    sa.Column('video_download_location', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
